// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/v1/payload.proto

package payloadpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StressTestService_Session_FullMethodName = "/stresstool.v1.StressTestService/Session"
)

// StressTestServiceClient is the client API for StressTestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StressTestServiceClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, ControllerMessage], error)
}

type stressTestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStressTestServiceClient(cc grpc.ClientConnInterface) StressTestServiceClient {
	return &stressTestServiceClient{cc}
}

func (c *stressTestServiceClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, ControllerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StressTestService_ServiceDesc.Streams[0], StressTestService_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeMessage, ControllerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StressTestService_SessionClient = grpc.BidiStreamingClient[NodeMessage, ControllerMessage]

// StressTestServiceServer is the server API for StressTestService service.
// All implementations must embed UnimplementedStressTestServiceServer
// for forward compatibility.
type StressTestServiceServer interface {
	Session(grpc.BidiStreamingServer[NodeMessage, ControllerMessage]) error
	mustEmbedUnimplementedStressTestServiceServer()
}

// UnimplementedStressTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStressTestServiceServer struct{}

func (UnimplementedStressTestServiceServer) Session(grpc.BidiStreamingServer[NodeMessage, ControllerMessage]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedStressTestServiceServer) mustEmbedUnimplementedStressTestServiceServer() {}
func (UnimplementedStressTestServiceServer) testEmbeddedByValue()                           {}

// UnsafeStressTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StressTestServiceServer will
// result in compilation errors.
type UnsafeStressTestServiceServer interface {
	mustEmbedUnimplementedStressTestServiceServer()
}

func RegisterStressTestServiceServer(s grpc.ServiceRegistrar, srv StressTestServiceServer) {
	// If the following call panics, it indicates UnimplementedStressTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StressTestService_ServiceDesc, srv)
}

func _StressTestService_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StressTestServiceServer).Session(&grpc.GenericServerStream[NodeMessage, ControllerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StressTestService_SessionServer = grpc.BidiStreamingServer[NodeMessage, ControllerMessage]

// StressTestService_ServiceDesc is the grpc.ServiceDesc for StressTestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StressTestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stresstool.v1.StressTestService",
	HandlerType: (*StressTestServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _StressTestService_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/payload.proto",
}
