// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/v1/payload.proto

package payloadpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NodeMessage_Hello
	//	*NodeMessage_Ready
	//	*NodeMessage_Progress
	//	*NodeMessage_TestResult
	//	*NodeMessage_Error
	Payload       isNodeMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_api_v1_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{0}
}

func (x *NodeMessage) GetPayload() isNodeMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NodeMessage) GetHello() *HelloMessage {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *NodeMessage) GetReady() *ReadyMessage {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *NodeMessage) GetProgress() *ProgressMessage {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *NodeMessage) GetTestResult() *TestResultMessage {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_TestResult); ok {
			return x.TestResult
		}
	}
	return nil
}

func (x *NodeMessage) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isNodeMessage_Payload interface {
	isNodeMessage_Payload()
}

type NodeMessage_Hello struct {
	Hello *HelloMessage `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type NodeMessage_Ready struct {
	Ready *ReadyMessage `protobuf:"bytes,2,opt,name=ready,proto3,oneof"`
}

type NodeMessage_Progress struct {
	Progress *ProgressMessage `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type NodeMessage_TestResult struct {
	TestResult *TestResultMessage `protobuf:"bytes,4,opt,name=test_result,json=testResult,proto3,oneof"`
}

type NodeMessage_Error struct {
	Error *ErrorMessage `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*NodeMessage_Hello) isNodeMessage_Payload() {}

func (*NodeMessage_Ready) isNodeMessage_Payload() {}

func (*NodeMessage_Progress) isNodeMessage_Payload() {}

func (*NodeMessage_TestResult) isNodeMessage_Payload() {}

func (*NodeMessage_Error) isNodeMessage_Payload() {}

type ControllerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControllerMessage_TestSpec
	//	*ControllerMessage_StartTests
	//	*ControllerMessage_Complete
	//	*ControllerMessage_StopTests
	Payload       isControllerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	mi := &file_api_v1_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{1}
}

func (x *ControllerMessage) GetPayload() isControllerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControllerMessage) GetTestSpec() *TestSpecMessage {
	if x != nil {
		if x, ok := x.Payload.(*ControllerMessage_TestSpec); ok {
			return x.TestSpec
		}
	}
	return nil
}

func (x *ControllerMessage) GetStartTests() *StartTestsMessage {
	if x != nil {
		if x, ok := x.Payload.(*ControllerMessage_StartTests); ok {
			return x.StartTests
		}
	}
	return nil
}

func (x *ControllerMessage) GetComplete() *CompleteMessage {
	if x != nil {
		if x, ok := x.Payload.(*ControllerMessage_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *ControllerMessage) GetStopTests() *StopTestsMessage {
	if x != nil {
		if x, ok := x.Payload.(*ControllerMessage_StopTests); ok {
			return x.StopTests
		}
	}
	return nil
}

type isControllerMessage_Payload interface {
	isControllerMessage_Payload()
}

type ControllerMessage_TestSpec struct {
	TestSpec *TestSpecMessage `protobuf:"bytes,1,opt,name=test_spec,json=testSpec,proto3,oneof"`
}

type ControllerMessage_StartTests struct {
	StartTests *StartTestsMessage `protobuf:"bytes,2,opt,name=start_tests,json=startTests,proto3,oneof"`
}

type ControllerMessage_Complete struct {
	Complete *CompleteMessage `protobuf:"bytes,3,opt,name=complete,proto3,oneof"`
}

type ControllerMessage_StopTests struct {
	StopTests *StopTestsMessage `protobuf:"bytes,4,opt,name=stop_tests,json=stopTests,proto3,oneof"`
}

func (*ControllerMessage_TestSpec) isControllerMessage_Payload() {}

func (*ControllerMessage_StartTests) isControllerMessage_Payload() {}

func (*ControllerMessage_Complete) isControllerMessage_Payload() {}

func (*ControllerMessage_StopTests) isControllerMessage_Payload() {}

type StopTestsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTestsMessage) Reset() {
	*x = StopTestsMessage{}
	mi := &file_api_v1_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTestsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTestsMessage) ProtoMessage() {}

func (x *StopTestsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTestsMessage.ProtoReflect.Descriptor instead.
func (*StopTestsMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{2}
}

func (x *StopTestsMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Funcs         []*FuncDef             `protobuf:"bytes,1,rep,name=funcs,proto3" json:"funcs,omitempty"`
	Tests         []*Test                `protobuf:"bytes,2,rep,name=tests,proto3" json:"tests,omitempty"`
	Auth          *AuthConfig            `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_api_v1_payload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{3}
}

func (x *Config) GetFuncs() []*FuncDef {
	if x != nil {
		return x.Funcs
	}
	return nil
}

func (x *Config) GetTests() []*Test {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *Config) GetAuth() *AuthConfig {
	if x != nil {
		return x.Auth
	}
	return nil
}

type AuthConfig struct {
	state                   protoimpl.MessageState         `protogen:"open.v1"`
	BasicAuth               *BasicAuthConfig               `protobuf:"bytes,1,opt,name=basic_auth,json=basicAuth,proto3" json:"basic_auth,omitempty"`
	Bearer                  *BearerAuthConfig              `protobuf:"bytes,2,opt,name=bearer,proto3" json:"bearer,omitempty"`
	ApiKey                  *APIKeyAuthConfig              `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Oauth2ClientCredentials *OAuth2ClientCredentialsConfig `protobuf:"bytes,4,opt,name=oauth2_client_credentials,json=oauth2ClientCredentials,proto3" json:"oauth2_client_credentials,omitempty"`
	Jwt                     *JWTAuthConfig                 `protobuf:"bytes,5,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AuthConfig) Reset() {
	*x = AuthConfig{}
	mi := &file_api_v1_payload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConfig) ProtoMessage() {}

func (x *AuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConfig.ProtoReflect.Descriptor instead.
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{4}
}

func (x *AuthConfig) GetBasicAuth() *BasicAuthConfig {
	if x != nil {
		return x.BasicAuth
	}
	return nil
}

func (x *AuthConfig) GetBearer() *BearerAuthConfig {
	if x != nil {
		return x.Bearer
	}
	return nil
}

func (x *AuthConfig) GetApiKey() *APIKeyAuthConfig {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

func (x *AuthConfig) GetOauth2ClientCredentials() *OAuth2ClientCredentialsConfig {
	if x != nil {
		return x.Oauth2ClientCredentials
	}
	return nil
}

func (x *AuthConfig) GetJwt() *JWTAuthConfig {
	if x != nil {
		return x.Jwt
	}
	return nil
}

// JWTAuthConfig carries JSON Web Token auth configuration. Header and payload
// are flat string key/value maps; numeric claims are coerced when the token
// is built.
type JWTAuthConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        map[string]string      `protobuf:"bytes,1,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload       map[string]string      `protobuf:"bytes,2,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Signature     *JWTSignatureConfig    `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTAuthConfig) Reset() {
	*x = JWTAuthConfig{}
	mi := &file_api_v1_payload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTAuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTAuthConfig) ProtoMessage() {}

func (x *JWTAuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTAuthConfig.ProtoReflect.Descriptor instead.
func (*JWTAuthConfig) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{5}
}

func (x *JWTAuthConfig) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *JWTAuthConfig) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *JWTAuthConfig) GetSignature() *JWTSignatureConfig {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *JWTAuthConfig) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type JWTSignatureConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTSignatureConfig) Reset() {
	*x = JWTSignatureConfig{}
	mi := &file_api_v1_payload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTSignatureConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTSignatureConfig) ProtoMessage() {}

func (x *JWTSignatureConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTSignatureConfig.ProtoReflect.Descriptor instead.
func (*JWTSignatureConfig) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{6}
}

func (x *JWTSignatureConfig) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type BasicAuthConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicAuthConfig) Reset() {
	*x = BasicAuthConfig{}
	mi := &file_api_v1_payload_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicAuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuthConfig) ProtoMessage() {}

func (x *BasicAuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuthConfig.ProtoReflect.Descriptor instead.
func (*BasicAuthConfig) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{7}
}

func (x *BasicAuthConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicAuthConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type BearerAuthConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BearerAuthConfig) Reset() {
	*x = BearerAuthConfig{}
	mi := &file_api_v1_payload_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BearerAuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BearerAuthConfig) ProtoMessage() {}

func (x *BearerAuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BearerAuthConfig.ProtoReflect.Descriptor instead.
func (*BearerAuthConfig) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{8}
}

func (x *BearerAuthConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type APIKeyAuthConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyAuthConfig) Reset() {
	*x = APIKeyAuthConfig{}
	mi := &file_api_v1_payload_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyAuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyAuthConfig) ProtoMessage() {}

func (x *APIKeyAuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyAuthConfig.ProtoReflect.Descriptor instead.
func (*APIKeyAuthConfig) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{9}
}

func (x *APIKeyAuthConfig) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *APIKeyAuthConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type OAuth2ClientCredentialsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenUrl      string                 `protobuf:"bytes,1,opt,name=token_url,json=tokenUrl,proto3" json:"token_url,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2ClientCredentialsConfig) Reset() {
	*x = OAuth2ClientCredentialsConfig{}
	mi := &file_api_v1_payload_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2ClientCredentialsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2ClientCredentialsConfig) ProtoMessage() {}

func (x *OAuth2ClientCredentialsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2ClientCredentialsConfig.ProtoReflect.Descriptor instead.
func (*OAuth2ClientCredentialsConfig) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{10}
}

func (x *OAuth2ClientCredentialsConfig) GetTokenUrl() string {
	if x != nil {
		return x.TokenUrl
	}
	return ""
}

func (x *OAuth2ClientCredentialsConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuth2ClientCredentialsConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *OAuth2ClientCredentialsConfig) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type FuncDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cmd           []string               `protobuf:"bytes,2,rep,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuncDef) Reset() {
	*x = FuncDef{}
	mi := &file_api_v1_payload_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuncDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuncDef) ProtoMessage() {}

func (x *FuncDef) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuncDef.ProtoReflect.Descriptor instead.
func (*FuncDef) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{11}
}

func (x *FuncDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FuncDef) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

type Test struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	Name              string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path              string                   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method            string                   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	RequestsPerSecond int32                    `protobuf:"varint,4,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	Threads           int32                    `protobuf:"varint,5,opt,name=threads,proto3" json:"threads,omitempty"`
	RunSeconds        int32                    `protobuf:"varint,6,opt,name=run_seconds,json=runSeconds,proto3" json:"run_seconds,omitempty"`
	Headers           map[string]string        `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body              string                   `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	Assert            *Assertion               `protobuf:"bytes,9,opt,name=assert,proto3" json:"assert,omitempty"`
	Nodes             map[string]*NodeOverride `protobuf:"bytes,10,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AuthDisabled      bool                     `protobuf:"varint,11,opt,name=auth_disabled,json=authDisabled,proto3" json:"auth_disabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Test) Reset() {
	*x = Test{}
	mi := &file_api_v1_payload_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{12}
}

func (x *Test) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Test) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Test) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Test) GetRequestsPerSecond() int32 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

func (x *Test) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *Test) GetRunSeconds() int32 {
	if x != nil {
		return x.RunSeconds
	}
	return 0
}

func (x *Test) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Test) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Test) GetAssert() *Assertion {
	if x != nil {
		return x.Assert
	}
	return nil
}

func (x *Test) GetNodes() map[string]*NodeOverride {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Test) GetAuthDisabled() bool {
	if x != nil {
		return x.AuthDisabled
	}
	return false
}

type NodeOverride struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestsPerSecond int32                  `protobuf:"varint,1,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	Threads           int32                  `protobuf:"varint,2,opt,name=threads,proto3" json:"threads,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeOverride) Reset() {
	*x = NodeOverride{}
	mi := &file_api_v1_payload_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeOverride) ProtoMessage() {}

func (x *NodeOverride) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeOverride.ProtoReflect.Descriptor instead.
func (*NodeOverride) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{13}
}

func (x *NodeOverride) GetRequestsPerSecond() int32 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

func (x *NodeOverride) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

type Assertion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	BodyContains  string                 `protobuf:"bytes,2,opt,name=body_contains,json=bodyContains,proto3" json:"body_contains,omitempty"`
	BodyEquals    string                 `protobuf:"bytes,3,opt,name=body_equals,json=bodyEquals,proto3" json:"body_equals,omitempty"`
	BodyNotEquals string                 `protobuf:"bytes,4,opt,name=body_not_equals,json=bodyNotEquals,proto3" json:"body_not_equals,omitempty"`
	MaxLatencyMs  int32                  `protobuf:"varint,5,opt,name=max_latency_ms,json=maxLatencyMs,proto3" json:"max_latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assertion) Reset() {
	*x = Assertion{}
	mi := &file_api_v1_payload_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assertion) ProtoMessage() {}

func (x *Assertion) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assertion.ProtoReflect.Descriptor instead.
func (*Assertion) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{14}
}

func (x *Assertion) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Assertion) GetBodyContains() string {
	if x != nil {
		return x.BodyContains
	}
	return ""
}

func (x *Assertion) GetBodyEquals() string {
	if x != nil {
		return x.BodyEquals
	}
	return ""
}

func (x *Assertion) GetBodyNotEquals() string {
	if x != nil {
		return x.BodyNotEquals
	}
	return ""
}

func (x *Assertion) GetMaxLatencyMs() int32 {
	if x != nil {
		return x.MaxLatencyMs
	}
	return 0
}

type HelloMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloMessage) Reset() {
	*x = HelloMessage{}
	mi := &file_api_v1_payload_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloMessage) ProtoMessage() {}

func (x *HelloMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloMessage.ProtoReflect.Descriptor instead.
func (*HelloMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{15}
}

func (x *HelloMessage) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HelloMessage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type TestSpecMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Parallel      bool                   `protobuf:"varint,3,opt,name=parallel,proto3" json:"parallel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestSpecMessage) Reset() {
	*x = TestSpecMessage{}
	mi := &file_api_v1_payload_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestSpecMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSpecMessage) ProtoMessage() {}

func (x *TestSpecMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSpecMessage.ProtoReflect.Descriptor instead.
func (*TestSpecMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{16}
}

func (x *TestSpecMessage) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *TestSpecMessage) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TestSpecMessage) GetParallel() bool {
	if x != nil {
		return x.Parallel
	}
	return false
}

type ProgressMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeName       string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	TestName       string                 `protobuf:"bytes,2,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	ElapsedSeconds float64                `protobuf:"fixed64,3,opt,name=elapsed_seconds,json=elapsedSeconds,proto3" json:"elapsed_seconds,omitempty"`
	TotalRequests  int64                  `protobuf:"varint,4,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	Failures       int64                  `protobuf:"varint,5,opt,name=failures,proto3" json:"failures,omitempty"`
	Rps            float64                `protobuf:"fixed64,6,opt,name=rps,proto3" json:"rps,omitempty"`
	Done           bool                   `protobuf:"varint,7,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProgressMessage) Reset() {
	*x = ProgressMessage{}
	mi := &file_api_v1_payload_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressMessage) ProtoMessage() {}

func (x *ProgressMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressMessage.ProtoReflect.Descriptor instead.
func (*ProgressMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{17}
}

func (x *ProgressMessage) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ProgressMessage) GetTestName() string {
	if x != nil {
		return x.TestName
	}
	return ""
}

func (x *ProgressMessage) GetElapsedSeconds() float64 {
	if x != nil {
		return x.ElapsedSeconds
	}
	return 0
}

func (x *ProgressMessage) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *ProgressMessage) GetFailures() int64 {
	if x != nil {
		return x.Failures
	}
	return 0
}

func (x *ProgressMessage) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *ProgressMessage) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type TestResultMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	TestName      string                 `protobuf:"bytes,2,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	Result        *TestResult            `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResultMessage) Reset() {
	*x = TestResultMessage{}
	mi := &file_api_v1_payload_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResultMessage) ProtoMessage() {}

func (x *TestResultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResultMessage.ProtoReflect.Descriptor instead.
func (*TestResultMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{18}
}

func (x *TestResultMessage) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TestResultMessage) GetTestName() string {
	if x != nil {
		return x.TestName
	}
	return ""
}

func (x *TestResultMessage) GetResult() *TestResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type TestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Test          *Test                  `protobuf:"bytes,1,opt,name=test,proto3" json:"test,omitempty"`
	Metrics       *Metrics               `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Assertions    *Assertions            `protobuf:"bytes,3,opt,name=assertions,proto3" json:"assertions,omitempty"`
	Passed        bool                   `protobuf:"varint,4,opt,name=passed,proto3" json:"passed,omitempty"`
	Errors        []string               `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	StoppedEarly  bool                   `protobuf:"varint,6,opt,name=stopped_early,json=stoppedEarly,proto3" json:"stopped_early,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResult) Reset() {
	*x = TestResult{}
	mi := &file_api_v1_payload_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResult) ProtoMessage() {}

func (x *TestResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResult.ProtoReflect.Descriptor instead.
func (*TestResult) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{19}
}

func (x *TestResult) GetTest() *Test {
	if x != nil {
		return x.Test
	}
	return nil
}

func (x *TestResult) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *TestResult) GetAssertions() *Assertions {
	if x != nil {
		return x.Assertions
	}
	return nil
}

func (x *TestResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *TestResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *TestResult) GetStoppedEarly() bool {
	if x != nil {
		return x.StoppedEarly
	}
	return false
}

type Assertions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assertions) Reset() {
	*x = Assertions{}
	mi := &file_api_v1_payload_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assertions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assertions) ProtoMessage() {}

func (x *Assertions) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assertions.ProtoReflect.Descriptor instead.
func (*Assertions) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{20}
}

type Metrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests     int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	SuccessCount      int64                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount      int64                  `protobuf:"varint,3,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	AssertionFailures int64                  `protobuf:"varint,4,opt,name=assertion_failures,json=assertionFailures,proto3" json:"assertion_failures,omitempty"`
	LatenciesNanos    []int64                `protobuf:"varint,5,rep,packed,name=latencies_nanos,json=latenciesNanos,proto3" json:"latencies_nanos,omitempty"`
	StatusCodes       map[int32]int64        `protobuf:"bytes,6,rep,name=status_codes,json=statusCodes,proto3" json:"status_codes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Errors            map[string]int64       `protobuf:"bytes,7,rep,name=errors,proto3" json:"errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_api_v1_payload_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{21}
}

func (x *Metrics) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *Metrics) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *Metrics) GetFailureCount() int64 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *Metrics) GetAssertionFailures() int64 {
	if x != nil {
		return x.AssertionFailures
	}
	return 0
}

func (x *Metrics) GetLatenciesNanos() []int64 {
	if x != nil {
		return x.LatenciesNanos
	}
	return nil
}

func (x *Metrics) GetStatusCodes() map[int32]int64 {
	if x != nil {
		return x.StatusCodes
	}
	return nil
}

func (x *Metrics) GetErrors() map[string]int64 {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ReadyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyMessage) Reset() {
	*x = ReadyMessage{}
	mi := &file_api_v1_payload_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyMessage) ProtoMessage() {}

func (x *ReadyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyMessage.ProtoReflect.Descriptor instead.
func (*ReadyMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{22}
}

func (x *ReadyMessage) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type StartTestsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTestsMessage) Reset() {
	*x = StartTestsMessage{}
	mi := &file_api_v1_payload_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTestsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTestsMessage) ProtoMessage() {}

func (x *StartTestsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTestsMessage.ProtoReflect.Descriptor instead.
func (*StartTestsMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{23}
}

func (x *StartTestsMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_api_v1_payload_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{24}
}

func (x *ErrorMessage) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ErrorMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ErrorMessage) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

type CompleteMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMessage) Reset() {
	*x = CompleteMessage{}
	mi := &file_api_v1_payload_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMessage) ProtoMessage() {}

func (x *CompleteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_payload_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMessage.ProtoReflect.Descriptor instead.
func (*CompleteMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_payload_proto_rawDescGZIP(), []int{25}
}

var File_api_v1_payload_proto protoreflect.FileDescriptor

const file_api_v1_payload_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/payload.proto\x12\rstresstool.v1\"\xba\x02\n" +
	"\vNodeMessage\x123\n" +
	"\x05hello\x18\x01 \x01(\v2\x1b.stresstool.v1.HelloMessageH\x00R\x05hello\x123\n" +
	"\x05ready\x18\x02 \x01(\v2\x1b.stresstool.v1.ReadyMessageH\x00R\x05ready\x12<\n" +
	"\bprogress\x18\x03 \x01(\v2\x1e.stresstool.v1.ProgressMessageH\x00R\bprogress\x12C\n" +
	"\vtest_result\x18\x04 \x01(\v2 .stresstool.v1.TestResultMessageH\x00R\n" +
	"testResult\x123\n" +
	"\x05error\x18\x05 \x01(\v2\x1b.stresstool.v1.ErrorMessageH\x00R\x05errorB\t\n" +
	"\apayload\"\xa2\x02\n" +
	"\x11ControllerMessage\x12=\n" +
	"\ttest_spec\x18\x01 \x01(\v2\x1e.stresstool.v1.TestSpecMessageH\x00R\btestSpec\x12C\n" +
	"\vstart_tests\x18\x02 \x01(\v2 .stresstool.v1.StartTestsMessageH\x00R\n" +
	"startTests\x12<\n" +
	"\bcomplete\x18\x03 \x01(\v2\x1e.stresstool.v1.CompleteMessageH\x00R\bcomplete\x12@\n" +
	"\n" +
	"stop_tests\x18\x04 \x01(\v2\x1f.stresstool.v1.StopTestsMessageH\x00R\tstopTestsB\t\n" +
	"\apayload\"*\n" +
	"\x10StopTestsMessage\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x90\x01\n" +
	"\x06Config\x12,\n" +
	"\x05funcs\x18\x01 \x03(\v2\x16.stresstool.v1.FuncDefR\x05funcs\x12)\n" +
	"\x05tests\x18\x02 \x03(\v2\x13.stresstool.v1.TestR\x05tests\x12-\n" +
	"\x04auth\x18\x03 \x01(\v2\x19.stresstool.v1.AuthConfigR\x04auth\"\xd8\x02\n" +
	"\n" +
	"AuthConfig\x12=\n" +
	"\n" +
	"basic_auth\x18\x01 \x01(\v2\x1e.stresstool.v1.BasicAuthConfigR\tbasicAuth\x127\n" +
	"\x06bearer\x18\x02 \x01(\v2\x1f.stresstool.v1.BearerAuthConfigR\x06bearer\x128\n" +
	"\aapi_key\x18\x03 \x01(\v2\x1f.stresstool.v1.APIKeyAuthConfigR\x06apiKey\x12h\n" +
	"\x19oauth2_client_credentials\x18\x04 \x01(\v2,.stresstool.v1.OAuth2ClientCredentialsConfigR\x17oauth2ClientCredentials\x12.\n" +
	"\x03jwt\x18\x05 \x01(\v2\x1c.stresstool.v1.JWTAuthConfigR\x03jwt\"\xef\x02\n" +
	"\rJWTAuthConfig\x12@\n" +
	"\x06header\x18\x01 \x03(\v2(.stresstool.v1.JWTAuthConfig.HeaderEntryR\x06header\x12C\n" +
	"\apayload\x18\x02 \x03(\v2).stresstool.v1.JWTAuthConfig.PayloadEntryR\apayload\x12?\n" +
	"\tsignature\x18\x03 \x01(\v2!.stresstool.v1.JWTSignatureConfigR\tsignature\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x05R\n" +
	"ttlSeconds\x1a9\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\x12JWTSignatureConfig\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\"I\n" +
	"\x0fBasicAuthConfig\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"(\n" +
	"\x10BearerAuthConfig\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"<\n" +
	"\x10APIKeyAuthConfig\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x96\x01\n" +
	"\x1dOAuth2ClientCredentialsConfig\x12\x1b\n" +
	"\ttoken_url\x18\x01 \x01(\tR\btokenUrl\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\"/\n" +
	"\aFuncDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03cmd\x18\x02 \x03(\tR\x03cmd\"\xa1\x04\n" +
	"\x04Test\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12.\n" +
	"\x13requests_per_second\x18\x04 \x01(\x05R\x11requestsPerSecond\x12\x18\n" +
	"\athreads\x18\x05 \x01(\x05R\athreads\x12\x1f\n" +
	"\vrun_seconds\x18\x06 \x01(\x05R\n" +
	"runSeconds\x12:\n" +
	"\aheaders\x18\a \x03(\v2 .stresstool.v1.Test.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\b \x01(\tR\x04body\x120\n" +
	"\x06assert\x18\t \x01(\v2\x18.stresstool.v1.AssertionR\x06assert\x124\n" +
	"\x05nodes\x18\n" +
	" \x03(\v2\x1e.stresstool.v1.Test.NodesEntryR\x05nodes\x12#\n" +
	"\rauth_disabled\x18\v \x01(\bR\fauthDisabled\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aU\n" +
	"\n" +
	"NodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.stresstool.v1.NodeOverrideR\x05value:\x028\x01\"X\n" +
	"\fNodeOverride\x12.\n" +
	"\x13requests_per_second\x18\x01 \x01(\x05R\x11requestsPerSecond\x12\x18\n" +
	"\athreads\x18\x02 \x01(\x05R\athreads\"\xc0\x01\n" +
	"\tAssertion\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12#\n" +
	"\rbody_contains\x18\x02 \x01(\tR\fbodyContains\x12\x1f\n" +
	"\vbody_equals\x18\x03 \x01(\tR\n" +
	"bodyEquals\x12&\n" +
	"\x0fbody_not_equals\x18\x04 \x01(\tR\rbodyNotEquals\x12$\n" +
	"\x0emax_latency_ms\x18\x05 \x01(\x05R\fmaxLatencyMs\"E\n" +
	"\fHelloMessage\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"y\n" +
	"\x0fTestSpecMessage\x12-\n" +
	"\x06config\x18\x01 \x01(\v2\x15.stresstool.v1.ConfigR\x06config\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x1a\n" +
	"\bparallel\x18\x03 \x01(\bR\bparallel\"\xdd\x01\n" +
	"\x0fProgressMessage\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x1b\n" +
	"\ttest_name\x18\x02 \x01(\tR\btestName\x12'\n" +
	"\x0felapsed_seconds\x18\x03 \x01(\x01R\x0eelapsedSeconds\x12%\n" +
	"\x0etotal_requests\x18\x04 \x01(\x03R\rtotalRequests\x12\x1a\n" +
	"\bfailures\x18\x05 \x01(\x03R\bfailures\x12\x10\n" +
	"\x03rps\x18\x06 \x01(\x01R\x03rps\x12\x12\n" +
	"\x04done\x18\a \x01(\bR\x04done\"\x80\x01\n" +
	"\x11TestResultMessage\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x1b\n" +
	"\ttest_name\x18\x02 \x01(\tR\btestName\x121\n" +
	"\x06result\x18\x03 \x01(\v2\x19.stresstool.v1.TestResultR\x06result\"\xf7\x01\n" +
	"\n" +
	"TestResult\x12'\n" +
	"\x04test\x18\x01 \x01(\v2\x13.stresstool.v1.TestR\x04test\x120\n" +
	"\ametrics\x18\x02 \x01(\v2\x16.stresstool.v1.MetricsR\ametrics\x129\n" +
	"\n" +
	"assertions\x18\x03 \x01(\v2\x19.stresstool.v1.AssertionsR\n" +
	"assertions\x12\x16\n" +
	"\x06passed\x18\x04 \x01(\bR\x06passed\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors\x12#\n" +
	"\rstopped_early\x18\x06 \x01(\bR\fstoppedEarly\"\f\n" +
	"\n" +
	"Assertions\"\xd5\x03\n" +
	"\aMetrics\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x03R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x03 \x01(\x03R\ffailureCount\x12-\n" +
	"\x12assertion_failures\x18\x04 \x01(\x03R\x11assertionFailures\x12'\n" +
	"\x0flatencies_nanos\x18\x05 \x03(\x03R\x0elatenciesNanos\x12J\n" +
	"\fstatus_codes\x18\x06 \x03(\v2'.stresstool.v1.Metrics.StatusCodesEntryR\vstatusCodes\x12:\n" +
	"\x06errors\x18\a \x03(\v2\".stresstool.v1.Metrics.ErrorsEntryR\x06errors\x1a>\n" +
	"\x10StatusCodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a9\n" +
	"\vErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"+\n" +
	"\fReadyMessage\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\"1\n" +
	"\x11StartTestsMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"W\n" +
	"\fErrorMessage\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\"\x11\n" +
	"\x0fCompleteMessage2`\n" +
	"\x11StressTestService\x12K\n" +
	"\aSession\x12\x1a.stresstool.v1.NodeMessage\x1a .stresstool.v1.ControllerMessage(\x010\x01B2Z0stresstool/internal/protocol/payloadpb;payloadpbb\x06proto3"

var (
	file_api_v1_payload_proto_rawDescOnce sync.Once
	file_api_v1_payload_proto_rawDescData []byte
)

func file_api_v1_payload_proto_rawDescGZIP() []byte {
	file_api_v1_payload_proto_rawDescOnce.Do(func() {
		file_api_v1_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_payload_proto_rawDesc), len(file_api_v1_payload_proto_rawDesc)))
	})
	return file_api_v1_payload_proto_rawDescData
}

var file_api_v1_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_api_v1_payload_proto_goTypes = []any{
	(*NodeMessage)(nil),                   // 0: stresstool.v1.NodeMessage
	(*ControllerMessage)(nil),             // 1: stresstool.v1.ControllerMessage
	(*StopTestsMessage)(nil),              // 2: stresstool.v1.StopTestsMessage
	(*Config)(nil),                        // 3: stresstool.v1.Config
	(*AuthConfig)(nil),                    // 4: stresstool.v1.AuthConfig
	(*JWTAuthConfig)(nil),                 // 5: stresstool.v1.JWTAuthConfig
	(*JWTSignatureConfig)(nil),            // 6: stresstool.v1.JWTSignatureConfig
	(*BasicAuthConfig)(nil),               // 7: stresstool.v1.BasicAuthConfig
	(*BearerAuthConfig)(nil),              // 8: stresstool.v1.BearerAuthConfig
	(*APIKeyAuthConfig)(nil),              // 9: stresstool.v1.APIKeyAuthConfig
	(*OAuth2ClientCredentialsConfig)(nil), // 10: stresstool.v1.OAuth2ClientCredentialsConfig
	(*FuncDef)(nil),                       // 11: stresstool.v1.FuncDef
	(*Test)(nil),                          // 12: stresstool.v1.Test
	(*NodeOverride)(nil),                  // 13: stresstool.v1.NodeOverride
	(*Assertion)(nil),                     // 14: stresstool.v1.Assertion
	(*HelloMessage)(nil),                  // 15: stresstool.v1.HelloMessage
	(*TestSpecMessage)(nil),               // 16: stresstool.v1.TestSpecMessage
	(*ProgressMessage)(nil),               // 17: stresstool.v1.ProgressMessage
	(*TestResultMessage)(nil),             // 18: stresstool.v1.TestResultMessage
	(*TestResult)(nil),                    // 19: stresstool.v1.TestResult
	(*Assertions)(nil),                    // 20: stresstool.v1.Assertions
	(*Metrics)(nil),                       // 21: stresstool.v1.Metrics
	(*ReadyMessage)(nil),                  // 22: stresstool.v1.ReadyMessage
	(*StartTestsMessage)(nil),             // 23: stresstool.v1.StartTestsMessage
	(*ErrorMessage)(nil),                  // 24: stresstool.v1.ErrorMessage
	(*CompleteMessage)(nil),               // 25: stresstool.v1.CompleteMessage
	nil,                                   // 26: stresstool.v1.JWTAuthConfig.HeaderEntry
	nil,                                   // 27: stresstool.v1.JWTAuthConfig.PayloadEntry
	nil,                                   // 28: stresstool.v1.Test.HeadersEntry
	nil,                                   // 29: stresstool.v1.Test.NodesEntry
	nil,                                   // 30: stresstool.v1.Metrics.StatusCodesEntry
	nil,                                   // 31: stresstool.v1.Metrics.ErrorsEntry
}
var file_api_v1_payload_proto_depIdxs = []int32{
	15, // 0: stresstool.v1.NodeMessage.hello:type_name -> stresstool.v1.HelloMessage
	22, // 1: stresstool.v1.NodeMessage.ready:type_name -> stresstool.v1.ReadyMessage
	17, // 2: stresstool.v1.NodeMessage.progress:type_name -> stresstool.v1.ProgressMessage
	18, // 3: stresstool.v1.NodeMessage.test_result:type_name -> stresstool.v1.TestResultMessage
	24, // 4: stresstool.v1.NodeMessage.error:type_name -> stresstool.v1.ErrorMessage
	16, // 5: stresstool.v1.ControllerMessage.test_spec:type_name -> stresstool.v1.TestSpecMessage
	23, // 6: stresstool.v1.ControllerMessage.start_tests:type_name -> stresstool.v1.StartTestsMessage
	25, // 7: stresstool.v1.ControllerMessage.complete:type_name -> stresstool.v1.CompleteMessage
	2,  // 8: stresstool.v1.ControllerMessage.stop_tests:type_name -> stresstool.v1.StopTestsMessage
	11, // 9: stresstool.v1.Config.funcs:type_name -> stresstool.v1.FuncDef
	12, // 10: stresstool.v1.Config.tests:type_name -> stresstool.v1.Test
	4,  // 11: stresstool.v1.Config.auth:type_name -> stresstool.v1.AuthConfig
	7,  // 12: stresstool.v1.AuthConfig.basic_auth:type_name -> stresstool.v1.BasicAuthConfig
	8,  // 13: stresstool.v1.AuthConfig.bearer:type_name -> stresstool.v1.BearerAuthConfig
	9,  // 14: stresstool.v1.AuthConfig.api_key:type_name -> stresstool.v1.APIKeyAuthConfig
	10, // 15: stresstool.v1.AuthConfig.oauth2_client_credentials:type_name -> stresstool.v1.OAuth2ClientCredentialsConfig
	5,  // 16: stresstool.v1.AuthConfig.jwt:type_name -> stresstool.v1.JWTAuthConfig
	26, // 17: stresstool.v1.JWTAuthConfig.header:type_name -> stresstool.v1.JWTAuthConfig.HeaderEntry
	27, // 18: stresstool.v1.JWTAuthConfig.payload:type_name -> stresstool.v1.JWTAuthConfig.PayloadEntry
	6,  // 19: stresstool.v1.JWTAuthConfig.signature:type_name -> stresstool.v1.JWTSignatureConfig
	28, // 20: stresstool.v1.Test.headers:type_name -> stresstool.v1.Test.HeadersEntry
	14, // 21: stresstool.v1.Test.assert:type_name -> stresstool.v1.Assertion
	29, // 22: stresstool.v1.Test.nodes:type_name -> stresstool.v1.Test.NodesEntry
	3,  // 23: stresstool.v1.TestSpecMessage.config:type_name -> stresstool.v1.Config
	19, // 24: stresstool.v1.TestResultMessage.result:type_name -> stresstool.v1.TestResult
	12, // 25: stresstool.v1.TestResult.test:type_name -> stresstool.v1.Test
	21, // 26: stresstool.v1.TestResult.metrics:type_name -> stresstool.v1.Metrics
	20, // 27: stresstool.v1.TestResult.assertions:type_name -> stresstool.v1.Assertions
	30, // 28: stresstool.v1.Metrics.status_codes:type_name -> stresstool.v1.Metrics.StatusCodesEntry
	31, // 29: stresstool.v1.Metrics.errors:type_name -> stresstool.v1.Metrics.ErrorsEntry
	13, // 30: stresstool.v1.Test.NodesEntry.value:type_name -> stresstool.v1.NodeOverride
	0,  // 31: stresstool.v1.StressTestService.Session:input_type -> stresstool.v1.NodeMessage
	1,  // 32: stresstool.v1.StressTestService.Session:output_type -> stresstool.v1.ControllerMessage
	32, // [32:33] is the sub-list for method output_type
	31, // [31:32] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_api_v1_payload_proto_init() }
func file_api_v1_payload_proto_init() {
	if File_api_v1_payload_proto != nil {
		return
	}
	file_api_v1_payload_proto_msgTypes[0].OneofWrappers = []any{
		(*NodeMessage_Hello)(nil),
		(*NodeMessage_Ready)(nil),
		(*NodeMessage_Progress)(nil),
		(*NodeMessage_TestResult)(nil),
		(*NodeMessage_Error)(nil),
	}
	file_api_v1_payload_proto_msgTypes[1].OneofWrappers = []any{
		(*ControllerMessage_TestSpec)(nil),
		(*ControllerMessage_StartTests)(nil),
		(*ControllerMessage_Complete)(nil),
		(*ControllerMessage_StopTests)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_payload_proto_rawDesc), len(file_api_v1_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_payload_proto_goTypes,
		DependencyIndexes: file_api_v1_payload_proto_depIdxs,
		MessageInfos:      file_api_v1_payload_proto_msgTypes,
	}.Build()
	File_api_v1_payload_proto = out.File
	file_api_v1_payload_proto_goTypes = nil
	file_api_v1_payload_proto_depIdxs = nil
}
